---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Welcome to my research website.

Click on this [link](simulations2.html) to see application of flash to simulated data with correlated factors.  <br /> 
Click on this [link](simulations3_update.html) to see application of flash to covariance matrix of simulated data with correlated factors. <br />
Click on this [link](simulations3_more.html) to see more replicates of application of flash to covariance matrix of simulated data with correlated factors. <br /> 
Click on this [link](simulations3_binary_general.html) to see application of flash to covariance matrix of simulated data with correlated factors with generalized binary prior vs point-exponential prior, using oracle initialization. <br /> 
Click on this [link](simulations3_binary_general_more.html) to see application of flash to covariance matrix of simulated data with correlated factors with generalized binary prior vs point-exponential prior, using greedy initialization. <br /> 
Click on this [link](twogroup.html) to see application of flash to covariance matrix of simulated data from two groups with shared factors. <br /> 
Click on this [link](presentation.html) to see illustration of a motivating example to analysis of single cell cancer data.  <br /> 
Click on this [link](simulations3_general_binary_normalmix.html) to see application of flash to covariance matrix of simulated data with correlated factors with generalized binary prior. <br /> 